
default_platform(:android)

platform :android do
  desc "Lane for android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:491945200189:android:e54679fc5e7382ba263854",
      firebase_cli_token: "1//035KSIUklJMFhCgYIARAAGAMSNwF-L9Ir_Ca9ic360IgKzLrinodarIqeog2L5yDhak52melEMP9INnD9JreSDaYmF74J5SIlLG0",	
      android_artifact_type: "APK" ,
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers: "abdo.agiry90@gmail.com",
      release_notes: "First Fastlane Firebase App Distribution"

    )
    
  end
end
